# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_studentinfo_guardian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='guardian',
        ),
    ]
